language: php

php:
  - 7.3
  - 7.4
  - 8.0snapshot

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer selfupdate --no-progress
  - travis_retry composer update --prefer-source $PREFER_LOWEST

script:
  - vendor/bin/phpcs  --standard=ruleset.xml --extensions=php -sp src tests --encoding=utf-8 --tab-width=4 --ignore=vendor
  - vendor/bin/phpunit tests --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

jobs:
  allow_failures:
    - php: 8.0snapshot
